### ISSUE TITLE
TELEM1 port baudrate changed to 115200, unable to connect to Micro USB port anymore.

### ISSUE THREAD

**Issue by wsolichin-bto** [SEESAI/Firmware#19]
By changing the SD Card settings in PX4 in /etc/extras.txt, unable to connect to the Micro USB port of Pixhawk device anymore to the computer. Need to connect to the computer via TELEM1 or TELEM2 port. Need to sort out how to connect to the Micro USB port of Pixhawk device.

**Comment by asimonov** [comment]
This issue was moved to SEESAI/Firmware-private#1
